# Generated by Django 5.2.3 on 2025-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_nom', models.CharField(max_length=100, null=True)),
                ('Client_prenom', models.CharField(max_length=100, null=True)),
                ('Client_cin', models.CharField(max_length=12, null=True, unique=True)),
                ('Client_photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/')),
                ('Client_adresse', models.TextField(null=True)),
                ('Client_quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('Client_telephone', models.CharField(max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
