# Generated by Django 5.2.3 on 2025-07-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='clerk_id',
        ),
        migrations.AddField(
            model_name='responsable',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
